In [ ]:
import numpy as np
import pandas as pd


In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
from pandas._libs.tslibs.offsets import DateOffset

dataset = pd.read_csv('/content/drive/MyDrive/dataset/Data.csv')
dataset


Country   Age   Salary Purchased
0       India  34.0  92000.0       Yes
1   Sri lanka  22.0  25000.0       Yes
2       China  31.0  74000.0       Yes
3   Sri lanka  29.0      NaN        No
4       China  55.0  98000.0       Yes
5       India  24.0  30000.0        No
6   Sri lanka  28.0  40000.0        No
7       India   NaN  60000.0        No
8       China  51.0  89000.0       Yes
9       India  44.0  78000.0       Yes
10  Sri lanka  21.0  20000.0        No
11      China  25.0  30000.0       Yes
12      India  33.0  45000.0       Yes
13      India  42.0  65000.0       Yes
14  Sri lanka  33.0  22000.0        No

In [ ]:
#find depended and in depended variable
#here country age and salary is indepeneded variable and purchased is depened variable
x =dataset[['Country','Age', 'Salary']]
# indepeneded variable

In [ ]:
x

Country   Age   Salary
0       India  34.0  92000.0
1   Sri lanka  22.0  25000.0
2       China  31.0  74000.0
3   Sri lanka  29.0      NaN
4       China  55.0  98000.0
5       India  24.0  30000.0
6   Sri lanka  28.0  40000.0
7       India   NaN  60000.0
8       China  51.0  89000.0
9       India  44.0  78000.0
10  Sri lanka  21.0  20000.0
11      China  25.0  30000.0
12      India  33.0  45000.0
13      India  42.0  65000.0
14  Sri lanka  33.0  22000.0

In [ ]:
x.values
x

Country   Age   Salary
0       India  34.0  92000.0
1   Sri lanka  22.0  25000.0
2       China  31.0  74000.0
3   Sri lanka  29.0      NaN
4       China  55.0  98000.0
5       India  24.0  30000.0
6   Sri lanka  28.0  40000.0
7       India   NaN  60000.0
8       China  51.0  89000.0
9       India  44.0  78000.0
10  Sri lanka  21.0  20000.0
11      China  25.0  30000.0
12      India  33.0  45000.0
13      India  42.0  65000.0
14  Sri lanka  33.0  22000.0

In [ ]:
y=dataset[['Purchased']].values
y

array([['Yes'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['No']], dtype=object)

In [ ]:
#find missing values
#2menthod
#1 we can removed row
#value replace find mean mode and median or traning the data
from sklearn.impute import SimpleImputer

In [ ]:
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')

In [ ]:
imputer = imputer.fit(x.iloc[:, 1:3])


In [ ]:
x.iloc[:, 1:3] = imputer.transform(x.iloc[:, 1:3])
x

<ipython-input-31-436aa81bb704>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x.iloc[:, 1:3] = imputer.transform(x.iloc[:, 1:3])


Country        Age        Salary
0       India  34.000000  92000.000000
1   Sri lanka  22.000000  25000.000000
2       China  31.000000  74000.000000
3   Sri lanka  29.000000  54857.142857
4       China  55.000000  98000.000000
5       India  24.000000  30000.000000
6   Sri lanka  28.000000  40000.000000
7       India  33.714286  60000.000000
8       China  51.000000  89000.000000
9       India  44.000000  78000.000000
10  Sri lanka  21.000000  20000.000000
11      China  25.000000  30000.000000
12      India  33.000000  45000.000000
13      India  42.000000  65000.000000
14  Sri lanka  33.000000  22000.000000

In [ ]:
#upper side we are handle missing data
#encodeing categorical data
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_encoder_x= LabelEncoder()


In [ ]:
x.iloc[:, 0] = label_encoder_x.fit_transform(x.iloc[:, 0])



<ipython-input-40-235baf33974d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x.iloc[:, 0] = label_encoder_x.fit_transform(x.iloc[:, 0])
<ipython-input-40-235baf33974d>:1: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  x.iloc[:, 0] = label_encoder_x.fit_transform(x.iloc[:, 0])


In [ ]:
x

Country        Age        Salary
0         1  34.000000  92000.000000
1         2  22.000000  25000.000000
2         0  31.000000  74000.000000
3         2  29.000000  54857.142857
4         0  55.000000  98000.000000
5         1  24.000000  30000.000000
6         2  28.000000  40000.000000
7         1  33.714286  60000.000000
8         0  51.000000  89000.000000
9         1  44.000000  78000.000000
10        2  21.000000  20000.000000
11        0  25.000000  30000.000000
12        1  33.000000  45000.000000
13        1  42.000000  65000.000000
14        2  33.000000  22000.000000

In [ ]:
#Dammy encodeing
from sklearn.preprocessing import OneHotEncoder

In [ ]:
OneHotEncoder=OneHotEncoder()

In [ ]:
# Fit and transform the 'Country' column
x = OneHotEncoder.fit_transform(dataset['Country'].values.reshape(-1, 1)).toarray()

In [ ]:
x

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#y ki valude alreasy yes no me tee to
# Initialize the LabelEncoder
labelencoder_y = LabelEncoder()

# Fit and transform the target variable 'y'
y = labelencoder_y.fit_transform(y)

In [ ]:
y

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0])

In [ ]:
#dataset split some data train and some data for test
from sklearn.model_selection import train_test_split

In [ ]:
#20% model sa test karnga fix result dega random result nhi dega issliy 0 rka
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=0)

In [ ]:
x_train

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [ ]:
x_test

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [ ]:
y_train

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1])

In [ ]:
y_test

array([1, 0, 1])

In [ ]:
#feature scaleing
#this is last step
from sklearn.preprocessing import StandardScaler

In [ ]:
sc_x=StandardScaler()

In [ ]:
x_train=sc_x.fit_transform(x_train)

In [ ]:
x_train = sc_x.transform(x_test)

In [ ]:
x_train


array([[-0.57735027, -1.        ,  1.73205081],
       [-0.57735027, -1.        ,  1.73205081],
       [ 1.73205081, -1.        , -0.57735027]])

In [ ]:
x_test

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [ ]:
#our model is ready to fit any model