In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
from pandas._libs.tslibs.offsets import DateOffset

df = pd.read_csv('/content/drive/MyDrive/dataset/insurance1.csv')
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


age   width  weight  primum
0   20  162.89      75   10000
1   25  155.42      65   20000
2   30  175.48      56   30000
3   35     NaN      52   40000
4   40  167.55      68   50000
5   45  145.00      72   60000
6   50  180.00      89   70000
7   55     NaN      66   80000

In [ ]:
# in this data set we are find where height is 165.56 and age is 27 weight is 60  . whoser age is 60 height is 165.10 and weight is 80

In [ ]:
from sklearn import linear_model

In [ ]:
#first we fill missing values mean mode and median
mean_width=df.width.mean()

In [ ]:
df.width

0    162.89
1    155.42
2    175.48
3       NaN
4    167.55
5    145.00
6    180.00
7       NaN
Name: width, dtype: float64

In [ ]:
#fill value width coloumn fill the value
df.width=df.width.fillna(mean_width)

In [ ]:
df

age   width  weight  primum
0   20  162.89      75   10000
1   25  155.42      65   20000
2   30  175.48      56   30000
3   35  164.39      52   40000
4   40  167.55      68   50000
5   45  145.00      72   60000
6   50  180.00      89   70000
7   55  164.39      66   80000

In [ ]:
reg=linear_model.LinearRegression()

In [ ]:
reg.fit(df[['age','width','weight']],df['primum'])

LinearRegression()

In [ ]:
reg.coef_

array([ 2.00000000e+03,  2.16549550e-13, -1.81412832e-14])

In [ ]:
reg.intercept_

-30000.00000000003

In [ ]:
reg.predict([[27,167.56,60]])
#here we are given age width and weight

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([24000.])

In [ ]:
# y=m1*x1+m2*x3+m3*x3+c
reg.predict([[100,167.56,60]])
#here we are given age width and weight


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([170000.])